Migrate to rubocop plugins
https://docs.rubocop.org/rubocop/plugin_migration_guide.html

Suppresses warnings in this repo and other repos that utilize it.

```
Error: rubocop-sorbet extension supports plugin, specify `plugins: rubocop-sorbet` instead of `require: rubocop-sorbet` in /opt/hostedtoolcache/Ruby/3.3.0/x64/lib/ruby/gems/3.3.0/gems/rubocop-sorbet-0.9.0/config/rbi.yml.
```

and

```
Specify `rubocop-internal_affairs` instead of `rubocop/cop/internal_affairs` in your configuration.
```