Check that `on_failure` is used with `checked(:{tests,always})`
- Our app had a PR that made it into our pre-production environment with
  Sorbet signatures that used `on_failure` without `checked(:tests)` or
  `checked(:always)`.
- Hence, we got an error that we had to rollback for, and I thought it
  would be a good candidate for a cop to catch this statically.

```
Exception: ArgumentError
Details: Error interpreting sig:
 To use .on_failure you must additionally call .checked(:tests) or .checked(:always), otherwise, the .on_failure has no effect.
```